# Generated by Django 6.0.5 on 2026-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('method', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.CharField(max_length=200)),
            ],
        ),
    ]
